[package]
name = "drive-light-client-bindings"
version = "0.1.0"
edition = "2021"
description = "This crate is only used to build bindings (using build.rs) for rs-drive-light-client and save them into bindings/"

[dependencies]
drive-light-client = { path = "../rs-drive-light-client", features = [
    "bindgen",
] }

[build-dependencies]

drive-light-client = { path = "../rs-drive-light-client", features = [
    "bindgen",
] }
