[package]
name = "platform-value-convertible"
authors = ["Samuel Westrich <sam@dash.org>"]
description = "Convertion to and from platform values"
version = "1.3.0-dev.5"
edition = "2021"
rust-version.workspace = true
license = "MIT"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.26"
syn = "2.0.15"
