[package]
name = "platform-value-convertible"
authors = ["Samuel Westrich <sam@dash.org>"]
description = "Convertion to and from platform values"
version = "1.0.0-pr.1621.0"
edition = "2021"
rust-version = "1.73"
license = "MIT"
private = true

[lib]
proc-macro = true

[dependencies]
quote = "1.0.26"
syn = "2.0.15"
