[package]
name = "dashpay-contract"
description = "DashPay data contract schema and tools"
version = "1.3.0-dev.5"
edition = "2021"
rust-version.workspace = true
license = "MIT"

[dependencies]
platform-version = { path = "../rs-platform-version" }
thiserror = "1.0.58"
serde_json = { version = "1.0" }
platform-value = { path = "../rs-platform-value" }
