[package]
name = "dashpay-contract"
description = "DashPay data contract schema and tools"
version = "1.0.0-pr.1694.7"
edition = "2021"
rust-version = "1.76"
license = "MIT"

[dependencies]
platform-version = { path = "../rs-platform-version" }
thiserror = "1.0.56"
serde_json = { version = "1.0" }
platform-value = { path = "../rs-platform-value" }
