[package]
name = "platform-serialization"
authors = ["Samuel Westrich <sam@dash.org>"]
description = "Bincode based serialization and deserialization"
version = "1.2.0"
edition = "2021"
rust-version.workspace = true
license = "MIT"

[dependencies]
bincode = { version = "2.0.0-rc.3", features = ["serde"] }
platform-version = { path = "../rs-platform-version" }
