[package]
name = "platform-serialization"
authors = ["Samuel Westrich <sam@dash.org>"]
description = "Bincode based serialization and deserialization"
version = "0.25.16-alpha.2"
edition = "2021"
rust-version = "1.73"
license = "MIT"
private = true

[dependencies]
bincode = { version = "2.0.0-rc.3", features = ["serde"] }
serde = { version = "1.0", default-features = false, optional = true }
platform-version = { path = "../rs-platform-version" }
