dist: bionic
language: node_js

node_js:
  - '12'

branches:
  only:
    - master
    - /^v(0|[1-9]\d*)\.(0|[1-9]\d*)-dev$/
    - /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce
      - jq

env:
  - DOCKER_COMPOSE_VERSION=1.25.5

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  - npm ci
  - cp .env.example .env
  # Get the latest version of travis-ci-tools
  - curl -u $GITHUB_USER:$GITHUB_TOKEN -s https://api.github.com/repos/dashevo/travis-ci-tools/releases/latest | jq -r '.tarball_url' | xargs -I {} -n1 wget -O travis-ci-tools.tar.gz -q {}
  - mkdir ~/travis-ci-tools && tar -C ~/travis-ci-tools -xvf travis-ci-tools.tar.gz
  - export CI_TOOLS_DIR="$(ls ~/travis-ci-tools)"
  - cd ~/travis-ci-tools/$CI_TOOLS_DIR
  - npm ci && npm link

before_script:
  - print-bells
  - source ./bin/start-local-node.sh $TRAVIS_BUILD_DIR/package.json --override-major-version=0 --dapi-branch=$DAPI_BRANCH --drive-branch=$DRIVE_BRANCH
  - cd $TRAVIS_BUILD_DIR
  # Build docker image
  - docker build -t platform-test-suite:local .

script: >
  npm run check-package &&
  npm run lint &&
  docker run --network="host" platform-test-suite:local 127.0.0.1:3000:3010 -k=$FAUCET_PRIVATE_KEY -n=regtest --dpns-tld-identity-private-key=$DPNS_TOP_LEVEL_IDENTITY_PRIVATE_KEY --dpns-tld-identity-id=$DPNS_TOP_LEVEL_IDENTITY_ID --dpns-contract-id=$DPNS_CONTRACT_ID

after_script:
  - mn stop

deploy:
  provider: script
  script: bash scripts/travis-deploy.sh
  on:
    tags: true
    repo: dashevo/platform-test-suite
