os: linux
language: node_js
node_js:
  - '8'
  - "10"
  - "12"

before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/travis-deploy.sh
    on:
      repo: dashevo/dash
      branch: master
