[package]
name = "random-document"
version = "1.0.0-dev.15"
edition = "2021"
rust-version = "1.76"
authors = [
  "Evgeny Fomin <evgeny.fomin@dash.org>",
  "Ivan Shumkov <shumkov@dash.ru>",
]

[dependencies]
json-schema-faker = { git = "https://github.com/fominok/json-schema-faker-rs", rev = "2dd1cf7" }
dpp = { path = "../rs-dpp", features = ["system_contracts", "document-value-conversion"] }
platform-value = { path = "../rs-platform-value", features = ["json"]}
anyhow = "1.0.86"
