[package]
name = "feature-flags-contract"
description = "Feature flags data contract schema and tools"
version = "0.26.0-dev.1"
edition = "2021"
rust-version = "1.73"
license = "MIT"

[dependencies]
serde_json = { version = "1.0" }
platform-value = { path = "../rs-platform-value" }
