[package]
name = "drive-nodejs"
version = "0.24.0-dev.1"
description = "GroveDB node.js bindings"
edition = "2021"
license = "MIT"
private = true

[lib]
crate-type = ["cdylib"]

[dependencies]
drive = { path = "../rs-drive", features = ["fixtures-and-mocks"]}
drive-abci = { path = "../rs-drive-abci" }
num = "0.4.0"
serde_json = { version="1.0", features=["preserve_order"] }

[dependencies.neon]
version = "0.10.1"
default-features = false
features = ["napi-6", "event-queue-api", "try-catch-api"]

[features]
enable-core-rpc-mocking = []
