[package]
name = "drive-nodejs"
version = "0.24.0-dev.1"
description = "GroveDB node.js bindings"
edition = "2021"
license = "MIT"
private = true

[lib]
crate-type = ["cdylib"]

[dependencies]
drive = { path = "../rs-drive" }
drive-abci = { path = "../rs-drive-abci" }
num = "0.4.0"
intmap = { version="2.0.0", features=["serde"] }

[dependencies.neon]
version = "0.10.1"
default-features = false
features = ["napi-6", "event-queue-api", "try-catch-api"]
