[package]
name = "node"
version = "0.23.0-dev.10"
description = "GroveDB node.js bindings"
edition = "2021"
license = "MIT"
private = true

[lib]
crate-type = ["cdylib"]

[dependencies]
rs-drive = { path = "../drive" }
dash-abci = { path = "../dash-abci" }
num = "0.4.0"

[dependencies.neon]
version = "0.10.1"
default-features = false
features = ["napi-6", "event-queue-api", "try-catch-api"]
