[package]
name = "node"
version = "0.22.0-dev.17"
description = "GroveDB node.js bindings"
edition = "2021"
license = "MIT"
private = true

[lib]
crate-type = ["cdylib"]

[dependencies]
rs-drive = { path = "../drive" }

[dependencies.grovedb]
git = "https://github.com/dashevo/grovedb"
branch = "develop"

[dependencies.neon]
version = "0.9"
default-features = false
features = ["napi-6", "event-queue-api", "try-catch-api"]
