os: linux
language: node_js
node_js:
  - '8'
  - "10"
  - "12"

before_install:
  - echo -e "machine github.com\n  login ${GH_TOKEN}" >> ~/.netrc
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: size
      script: npm run size

deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/travis-deploy.sh
    on:
      repo: dashevo/wallet-lib
      branch: master
