name: DAPI gRPC

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - v[0-9]+\.[0-9]+-dev
    paths:
      - .github/workflows/dapi-grpc.yml
      - .github/workflows/test.yml
      - packages/dapi-grpc/**
      - packages/js-grpc-common/**

jobs:
  dapi-tests:
    name: Run DAPI gRPC tests
    uses: dashevo/platform/.github/workflows/test.yml@feat-yarn2
    with:
      package: '@dashevo/dapi-grpc'
