name: Dash SPV

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - v[0-9]+\.[0-9]+-dev
    paths:
      - .github/workflows/dash-spv.yml
      - .github/workflows/test.yml
      - packages/dash-spv/**

jobs:
  dash-spv-tests:
    name: Run Dash SPV tests
    uses: ./.github/workflows/test.yml
    with:
      package: 'dash-spv'
      start-local-network: false
