name: Dash SPV

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - v[0-9]+\.[0-9]+-dev
    paths:
      - .github/workflows/js-dash-spv.yml
      - .github/workflows/test.yml
      - packages/js-dash-spv/**
      - packages/js-dapi-client/**
      - packages/dapi-grpc/**
      - packages/js-dpp/**
      - packages/js-grpc-common/**
      - packages/dashpay-contract/**
      - packages/feature-flags-contract/**
      - packages/dpns-contract/**
      - packages/masternode-reward-shares-contract/**

jobs:
  js-dash-sdk-tests:
    name: Run Dash SPV tests
    uses: dashevo/platform/.github/workflows/test.yml@master
    with:
      package: 'dash-spv'
      start-local-network: false
