name: JS DPP

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - v[0-9]+\.[0-9]+-dev
    paths:
      - .github/workflows/js-dpp.yml
      - .github/workflows/include/js-checks.yml
      - packages/js-dpp/**
      - packages/feature-flags-contract/**
      - packages/masternode-reward-shares-contract/**
      - packages/dpns-contract/**
      - packages/dashpay-contract/**
  schedule:
    - cron: '30 4 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  js-dpp-tests:
    name: JS checks
    uses: ./.github/workflows/include/js-checks.yml
    with:
      package: '@dashevo/dpp'
      install-browsers: true
