name: DPP

on:
  workflow_dispatch:
  release:
    types:
      - published
  pull_request:
    branches:
      - master
      - v[0-9]+\.[0-9]+-dev
    paths:
      - .github/workflows/js-dpp.yml
      - .github/workflows/test.yml
      - packages/js-dpp/**
      - packages/feature-flags-contract/**
      - packages/dpns-contract/**
      - packages/dashpay-contract/**

jobs:
  js-dpp-tests:
    name: Run DPP tests
    uses: dashevo/platform/.github/workflows/test.yml@optimize-build
    with:
      package: '@dashevo/dpp'
