---
name: RS Drive ABCI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - v[0-9]+\.[0-9]+-dev
      - phoenix
    paths:
      - .github/workflows/rs-drive-abci.yml
      - .github/workflows/rs-checks.yml
      - packages/feature-flags-contract/**
      - packages/dpns-contract/**
      - packages/dashpay-contract/**
      - packages/masternode-reward-shares-contract/**
      - packages/rs-dpp/**
      - packages/rs-drive/**
      - packages/rs-drive-abci/**
      - packages/rs-platform-value/**
  schedule:
    - cron: "30 4 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rs-checks:
    name: Rust
    uses: ./.github/workflows/rs-checks.yml
    with:
      package: "drive-abci"

# TODO: Remove?
#  docker:
#    name: Docker
#    runs-on: self-hosted
#    timeout-minutes: 180  # ARM build can take forever
#    steps:
#      - uses: actions/checkout@v3
#      - uses: ./.github/actions/docker
#        with:
#          dockerfile: ./Dockerfile
#          image: dashpay/drive-abci
#          target: drive-abci
#          push: false
