name: RS Drive

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - v[0-9]+\.[0-9]+-dev
    paths:
      - .github/workflows/rs-drive.yml
      - .github/workflows/rs-checks.yml
      - packages/feature-flags-contract/**
      - packages/dpns-contract/**
      - packages/dashpay-contract/**
      - packages/masternode-reward-shares-contract/**
      - packages/rs-dpp/**
  schedule:
    - cron: '30 4 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  feature-compilation:
    name: Feature compilation errors
    runs-on: ubuntu-22-04
    timeout-minutes: 20
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      - name: Enable Rust Cache
        uses: Swatinem/rust-cache@v2

      - run: cargo check --package=drive --no-default-features --features=verify

  rs-checks:
    name: Rust
    uses: ./.github/workflows/rs-checks.yml
    with:
      package: 'drive'
