version: '3.7'

services:
  dapi_tx_filter_stream:
    build:
      context: ${PLATFORM_DAPI_API_DOCKER_BUILD_CONTEXT:?err}
      dockerfile: ${PLATFORM_DAPI_API_DOCKER_BUILD_DOCKER_FILE:?err}
      target: ${PLATFORM_DAPI_API_DOCKER_BUILD_DOCKER_TARGET:?err}
    image: dapi:local
